Compiles with internal Lua, PNG and JPEG!
... but fails linking on p3dpluglua.cpp with:
scons: *** [extern/libs/libext_lua.a] AttributeError : 'map' object has no attribute 'get_ninfo'
scons: building terminated because of errors.